version: "3.9"
services:
  app:
    build: ./app
    container_name: w9-app
    ports: ["8001:8001"]

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: w9-prometheus
    ports: ["9091:9090"]
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/rules:/etc/prometheus/rules:ro
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    depends_on: [app]

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: w9-alertmanager
    ports: ["9094:9094"]
    volumes:
      - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command: ["--config.file=/etc/alertmanager/alertmanager.yml"]
    depends_on: [prometheus, alert-listener]

  alert-listener:
    build: ./monitoring/alert-listener
    container_name: w9-alert-listener
    ports: ["5001:5001"]
    volumes:
      - ./monitoring/alert-listener-data:/var/log/alerts

  grafana:
    image: grafana/grafana:10.4.2
    container_name: w9-grafana
    ports: ["3001:3000"]
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/w9-fastapi.json
    depends_on: [prometheus]

  drift-sim:
    build:
      context: ./drift
      dockerfile: sim.Dockerfile
    container_name: w9-drift-sim
    volumes:
      - ./data:/data
    restart: unless-stopped


  drift-exporter:
    build: ./drift/exporter
    container_name: w9-drift-exporter
    ports: ["8002:8002"]
    environment:
      - DATA_DIR=/data
      - REPORT_DIR=/reports
      - EVAL_INTERVAL_SEC=15
      - DATASET_LABEL=demo
    volumes:
      - ./data:/data
      - ./reports:/reports
    depends_on:
      - drift-sim

