global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]   # container:port

rule_files:
  - /etc/prometheus/rules/*.yml            # load our rules

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]        # self-scrape in-container

  - job_name: w9-app
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8001"]

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "w9-app"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8001"]

  - job_name: "evidently-drift"
    metrics_path: /metrics
    static_configs:
      - targets: ["drift-exporter:8002"]

