name: CI - W9 D1

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          # If you have project requirements, install them first
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          # Ensure pytest is present
          pip install pytest
          # Your explicit runtime dep from before
          pip install requests

      - name: Check Python & pytest
        run: |
          python --version
          pytest --version

      - name: Start stack
        run: |
          docker compose up -d --build
          # wait a bit for app to start
          sleep 10

      - name: Run tests
        env:
          PYTHONDONTWRITEBYTECODE: "1"
        run: |
          python -m pytest -q

      - name: Stop stack
        if: always()
        run: docker compose down -v
