name: CI - W9 D1

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Start stack
        run: |
          docker compose up -d --build
          # wait a bit for app to start
          sleep 10
      - name: Run tests
        run: python -m pytest -q
      - name: Stop stack
        if: always()
        run: docker compose down -v
